/**
 * Pro surface for @affino/datagrid-vue.
 * Includes the full stable API plus worker/server/pivot heavy primitives.
 */

export * from "./public"

export {
  createDataSourceBackedRowModel,
  createServerBackedRowModel,
  createServerRowModel,
  createDataGridServerPivotRowId,
  normalizeDataGridAdvancedFilterExpression,
  normalizePivotSpec,
  clonePivotSpec,
  isSamePivotSpec,
} from "@affino/datagrid-core/pro"

export type {
  DataGridApiPivotNamespace,
  DataGridPivotSpec,
  DataGridPivotValueSpec,
  DataGridPivotColumn,
  DataGridPivotColumnPathSegment,
  DataGridPivotCellDrilldownInput,
  DataGridPivotCellDrilldown,
  DataGridPivotLayoutColumnState,
  DataGridPivotLayoutSnapshot,
  DataGridPivotLayoutImportOptions,
  DataGridPivotInteropSnapshot,
  DataGridDataSource,
  DataGridDataSourceBackpressureDiagnostics,
  DataGridDataSourceInvalidation,
  DataGridDataSourcePaginationPullContext,
  DataGridDataSourcePullPriority,
  DataGridDataSourcePivotPullContext,
  DataGridDataSourcePullReason,
  DataGridDataSourcePullRequest,
  DataGridDataSourcePullResult,
  DataGridDataSourceTreePullContext,
  DataGridDataSourceTreePullOperation,
  DataGridDataSourceTreePullScope,
  DataGridDataSourcePushEvent,
  DataGridDataSourcePushInvalidateEvent,
  DataGridDataSourcePushListener,
  DataGridDataSourcePushRemoveEvent,
  DataGridDataSourcePushUpsertEvent,
  DataGridDataSourceRowEntry,
  DataGridServerPivotRowIdInput,
  DataGridServerPivotRowRole,
  DataSourceBackedRowModel,
  CreateDataSourceBackedRowModelOptions,
  ServerBackedRowModel,
  CreateServerBackedRowModelOptions,
  ServerRowModel,
  ServerRowModelOptions,
  ServerRowModelFetchResult,
  DataGridClientComputeDiagnostics,
  DataGridClientComputeRequest,
  DataGridClientComputeTransport,
  DataGridClientComputeTransportResult,
} from "@affino/datagrid-core/pro"

export {
  DATAGRID_WORKER_PROTOCOL_CHANNEL,
  DATAGRID_WORKER_PROTOCOL_VERSION,
  DATAGRID_WORKER_ROW_MODEL_PROTOCOL_CHANNEL,
  DATAGRID_WORKER_ROW_MODEL_PROTOCOL_VERSION,
  createDataGridWorkerComputeRequestMessage,
  createDataGridWorkerComputeAckMessage,
  createDataGridWorkerComputeErrorAckMessage,
  createDataGridWorkerRowModelCommandMessage,
  createDataGridWorkerRowModelUpdateMessage,
  isDataGridWorkerComputeRequestMessage,
  isDataGridWorkerComputeAckMessage,
  isDataGridWorkerRowModelCommandMessage,
  isDataGridWorkerRowModelUpdateMessage,
  createDataGridWorkerPostMessageTransport,
  createDataGridWorkerMessageHost,
  createDataGridWorkerOwnedRowModelHost,
  createDataGridWorkerOwnedRowModel,
} from "@affino/datagrid-worker"

export type {
  DataGridWorkerComputeRequest,
  DataGridWorkerComputeResult,
  DataGridWorkerProtocolHeader,
  DataGridWorkerComputeRequestMessage,
  DataGridWorkerComputeAckMessage,
  DataGridWorkerProtocolMessage,
  DataGridWorkerMessageEvent,
  DataGridWorkerMessageSource,
  DataGridWorkerMessageTarget,
  DataGridWorkerDispatchStrategy,
  DataGridWorkerPostMessageTransportStats,
  DataGridWorkerPostMessageTransport,
  CreateDataGridWorkerPostMessageTransportOptions,
  CreateDataGridWorkerMessageHostOptions,
  DataGridWorkerMessageHost,
  DataGridWorkerRowModelProtocolHeader,
  DataGridWorkerViewportCoalesceScope,
  DataGridWorkerRowModelCommand,
  DataGridWorkerRowModelCommandMessage,
  DataGridWorkerRowModelUpdatePayload,
  DataGridWorkerRowModelUpdateMessage,
  DataGridWorkerRowModelProtocolMessage,
  CreateDataGridWorkerOwnedRowModelHostOptions,
  DataGridWorkerOwnedRowModelHost,
  DataGridWorkerOwnedRowModel,
  CreateDataGridWorkerOwnedRowModelOptions,
} from "@affino/datagrid-worker"
